AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - API Gateway REST -> SQS

Parameters:
  Environment:
    Description: Which environment to deploy the lambda to.
    Type: String
    AllowedValues:
      - stage
      - live
    Default: stage

Resources:
  GraphQLAPI:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      SchemaUri: ./src/schema/schema.graphql
      Auth:
        Type: API_KEY
      ApiKeys:
        OnlyToRead: {}

Outputs:
  APIEndpoint:
    Description: GraphQLAPI API Endpoint
    Value: !GetAtt GraphQLAPI.GraphQLUrl

  ApiKey:
    Description: API Key for authentication
    Value: !GetAtt GraphQLAPIOnlyToRead.ApiKey

  ApiId:
    Description: GraphQLAPI ID
    Export:
      Name: !Sub '${Environment}-graphql-api'
    Value:
      Fn::GetAtt: GraphQLAPI.ApiId
