/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 --transform public/house.glb --types 
Files: public/house.glb [1.05MB] > /Users/adamhorne/Documents/portfolio/apps/house/house-transformed.glb [30.74KB] (97%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

// import houseModel from '../../../assets/house-transformed.glb?url'

const imgUrl = new URL('../../../assets/house-transformed.glb', import.meta.url).href

type GLTFResult = GLTF & {
  nodes: {
    floorplan: THREE.Mesh
    Plane: THREE.Mesh
    Cabinet1: THREE.Mesh
  }
  materials: {
    floorplan: THREE.MeshStandardMaterial
    Cabinet_material: THREE.MeshStandardMaterial
  }
  animations: ''
}

export function House(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(imgUrl) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.floorplan.geometry}
        material={materials.floorplan}
        position={[1.892, -0.042, -0.343]}
        rotation={[0, 1.571, 0]}
        scale={17.477}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0.228, -0.042, 3.013]}
        scale={0.079}
      />
      <mesh
        geometry={nodes.Cabinet1.geometry}
        material={materials.Cabinet_material}
        position={[-0.911, 0.16, 5.352]}
        rotation={[Math.PI, 0, Math.PI]}
      />
    </group>
  )
}

useGLTF.preload(imgUrl)
