version = 0.1
[default.deploy.parameters]
stack_name = "app-madamot-storybook"
resolve_s3 = true
s3_prefix = "app-madamot-storybook"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
