version = 0.1
[default.deploy.parameters]
stack_name = "madamot-graphql"
resolve_s3 = true
s3_prefix = "madamot-graphql"
region = "eu-west-1"
profile = "madamotadam-adminaccess"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
