version = 0.1
[default.deploy.parameters]
stack_name = "apps-madamot"
resolve_s3 = true
s3_prefix = "apps-madamot"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
