version = 0.1
[default.deploy.parameters]
stack_name = "page-rebuild-all"
resolve_s3 = true
s3_prefix = "page-rebuild-all"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
