AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway for services

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

Outputs:
  ApiGatewayArn:
    Description: API Gateway ARN
    Export:
      Name: ApiGatewayArn
    Value:
      Fn::GetAtt: ApiGatewayApi.Arn
