## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The webhook DatoCMS hits on publish in order to make a request back to DatoCMS order to get the page data and save it as a json file in s3

Parameters:
  Environment:
    Description: Which environment to deploy the lambda to.
    Type: String
    AllowedValues:
      - stage
      - live
    Default: stage

Resources:
  ##########################################################################
  #   Lambda Function                                                      #
  ##########################################################################
  webhookHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-page-cache'
      Description: A DatoCMS webhook handler
      CodeUri: dist/
      Handler: app.handler
      Runtime: nodejs16.x
      Policies:
        - S3FullAccessPolicy:
            BucketName: page-madamot-live-cache # bucket name without arn
        - S3FullAccessPolicy:
            BucketName: page-madamot-live-preview-cache
        - SNSPublishMessagePolicy:
            TopicName: !ImportValue SNSTopicName
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: 'arn:aws:secretsmanager:eu-west-1:745413044589:secret:DatoCMS/page-deploy-site/API_KEY-uNpJBp'
      Timeout: 10
      Environment:
        Variables:
          someSecret: '{{resolve:secretsmanager:DatoCMS/page-deploy-site/API_KEY}}'
          TOPIC_NAME: !ImportValue SNSTopicArn

##########################################################################
#   Stack outputs                                                        #
##########################################################################
Outputs:
  webhookHandler:
    Description: The subnet ID to use for public web servers
    Export:
      Name: !Sub '${Environment}-cache'
    Value:
      Fn::GetAtt: webhookHandler.Arn
