## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The webhook DatoCMS hits on publish in order to make a request back to DatoCMS order to get the page data and save it as a json file in s3

Resources:
  ##########################################################################
  #   Lambda Function                                                      #
  ##########################################################################
  webhookHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: A DatoCMS webhook handler
      CodeUri: dist/
      Handler: app.handler
      Runtime: nodejs16.x
      Policies:
        - S3FullAccessPolicy:
            BucketName: pages-madamot-live-cache # bucket name without arn
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: 'arn:aws:secretsmanager:eu-west-1:745413044589:secret:DatoCMS/page-deploy-site/API_KEY-uNpJBp'
      Timeout: 10
      Environment:
        Variables:
          someSecret: '{{resolve:secretsmanager:DatoCMS/page-deploy-site/API_KEY}}'
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST

##########################################################################
#   Stack outputs                                                        #
##########################################################################
Outputs:
  GitHubEndpoint:
    Description: 'The build invocation URl to provide to DatoCMS webhook'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
