## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Handles events received from DatoCMS

Resources:
  ##########################################################################
  #   Lambda Function                                                      #
  ##########################################################################
  webhookHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handles events received from DatoCMS
      CodeUri: dist/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 60
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !ImportValue CmsSqsQueueArn
            BatchSize: 10
