## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The webhook DatoCMS hits on the build trigger to rebuild the whole site

Resources:
  ##########################################################################
  #   Lambda Function                                                      #
  ##########################################################################
  webhookHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Rebuild all pages in datoCMS
      CodeUri: dist/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 60
      Environment:
        Variables:
          someSecret: '{{resolve:secretsmanager:DatoCMS/page-deploy-site/API_KEY}}'
          TOPIC_NAME: !ImportValue SNSTopicArn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !ImportValue CmsSqsQueueArn
            BatchSize: 10

##########################################################################
#   Stack outputs                                                        #
##########################################################################
Outputs:
  DatoCMSEndpoint:
    Description: 'The site rebuild URl to provide to datoCMS build trigger webhook'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
