AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sends notifications from S3 to SNS when site data has been inserted into page-madamot-live-cache

Resources:
  ## S3 bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: page-madamot-live-cache

  PreviewSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: page-madamot-live-preview-cache

  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: page-madamot-stage-cache

  PreviewSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: page-madamot-stage-preview-cache

