AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sends notifications from S3 to SNS when site data has been inserted into page-madamot-live-cache

Resources:
  CmsSqsQueue:
    Type: AWS::SQS::Queue

Outputs:
  CmsSqsQueueArn:
    Description: CMS SQS Queue ARN
    Export:
      Name: CmsSqsQueueArn
    Value:
      Fn::GetAtt: CmsSqsQueue.Arn
