version = 0.1
[stage.deploy.parameters]
stack_name = "stage-graphql-page-service"
resolve_s3 = true
s3_prefix = "stage-graphql-page-service"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []

[live.deploy.parameters]
stack_name = "live-graphql-page-service"
resolve_s3 = true
s3_prefix = "live-graphql-page-service"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
